[package]
name = "opengl_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1"
ultraviolet = "0.7"
gl = "0.14.0"
gl_loader = "0.1.0" 
beryllium = "0.13.3"
imagine = "0.0.5"

[dev-dependencies]